export const defaultStrategicGameImage = '/static/images/generic/strategic.png';
export const defaultFactionImage = '/static/images/avatars/avatar-001.png';

export const getGenericImages = () => {
  return [
    '/static/images/avatars/avatar-000.png',
    '/static/images/avatars/avatar-001.png',
    '/static/images/avatars/avatar-002.png',
    '/static/images/avatars/avatar-003.png',
    '/static/images/avatars/avatar-004.png',
    '/static/images/avatars/avatar-005.png',
    '/static/images/avatars/avatar-006.png',
    '/static/images/avatars/avatar-007.png',
    '/static/images/avatars/avatar-008.png',
    '/static/images/avatars/avatar-009.png',
    '/static/images/avatars/avatar-010.png',
    '/static/images/avatars/avatar-011.png',
    '/static/images/avatars/avatar-012.png',
    '/static/images/avatars/avatar-013.png',
    '/static/images/avatars/avatar-014.png',
    '/static/images/avatars/avatar-015.png',
    '/static/images/generic/strategic.png',
    '/static/images/generic/map.png',
    '/static/images/generic/tactical.png',
    '/static/images/generic/armor-shield.png',
    '/static/images/races/generic-dark-human-01.png',
    '/static/images/races/generic-desert-human-01.png',
    '/static/images/races/generic-dwarf-01.png',
    '/static/images/races/generic-east-human-01.png',
    '/static/images/races/generic-elf-01.png',
    '/static/images/races/generic-grey-elf-01.png',
    '/static/images/races/generic-halfling-01.png',
    '/static/images/races/generic-high-elf-01.png',
    '/static/images/races/generic-high-human-01.png',
    '/static/images/races/generic-high-orc-01.png',
    '/static/images/races/generic-horse-human-01.png',
    '/static/images/races/generic-human-01.png',
    '/static/images/races/generic-human-02.png',
    '/static/images/races/generic-lesser-orc-01.png',
    '/static/images/races/generic-orc-01.png',
    '/static/images/races/generic-orc-02.png',
    '/static/images/races/generic-orc-05.png',
    '/static/images/races/generic-troll-01.png',
    '/static/images/races/generic-troll-02.png',
    '/static/images/races/generic-war-troll-01.png',
    '/static/images/races/generic-wood-elf-01.png',
    '/static/images/races/generic-wood-human-01.png',
    '/static/images/races/sauron.png',
    '/static/images/races/unknown.png',
  ];
};
